version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat-db
      POSTGRES_USER: akamf
      POSTGRES_PASSWORD: s3cr37
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend
    environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:5432/postgres
      #SPRING_DATASOURCE_USERNAME: postgres.dcdmidsgamsyejqvjzfe
      #SPRING_DATASOURCE_PASSWORD: UD5JMJVj6t7T_QW
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat-db
      SPRING_DATASOURCE_USERNAME: akamf
      SPRING_DATASOURCE_PASSWORD: s3cr37

    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
        - chat-net

  frontend:
    build:
      context: ../live-chat-frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:80"
    networks:
      - chat-net

volumes:
  postgres_data:

networks:
  chat-net: