version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat-db
      POSTGRES_USER: akamf
      POSTGRES_PASSWORD: s3cr37
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat-db
      SPRING_DATASOURCE_USERNAME: akamf
      SPRING_DATASOURCE_PASSWORD: s3cr37
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
        - chat-net

volumes:
  postgres_data:

networks:
  chat-net: