spring:
  application:
    name: live-chat-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-db
    username: akamf
    password: s3cr37
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # TODO: Change to validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
