spring:
  application:
    name: live-chat-backend

  config:
    import: optional:file:.env[.properties]

  security:
    user:
      name: user
      password: secret
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      maxLifetime: 1800000
      idleTimeout: 600000
      poolName: LiveChatHikariPool

  sql:
    init:
      platform: postgresql
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        boot:
          allow_jdbc_metadata_access: false
        show_sql: false

server:
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.hibernate.SQL: ERROR
