spring:
  application:
    name: live-chat-backend

  security:
    user:
      name: user
      password: secret
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: ${CLERK_ISSUER_URL}
            issuer-uri: https://lasting-lark-17.clerk.accounts.dev

  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:5432/postgres
    username: postgres.dcdmidsgamsyejqvjzfe
    password: UD5JMJVj6t7T_QW
    driver-class-name: org.postgresql.Driver

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  sql:
    init:
      platform: postgresql
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

server:
  port: 8080

debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
