spring:
  application:
    name: live-chat-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat-db}
    username: ${SPRING_DATASOURCE_USERNAME:akamf}
    password: ${SPRING_DATSOURCE_PASSWORD:s3cr37}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # TODO: Change to validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: 8080
