spring:
  application:
    name: live-chat-backend

  config:
    import: optional:file:.env[.properties]

  security:
    user:
      name: user
      password: secret
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URL}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  sql:
    init:
      platform: postgresql
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
